/**
 * Integration tests for the full generate() pipeline.
 *
 * These tests load the real openapi.yaml from the project root and assert on
 * the shape of the three output files produced by generate().  No files are
 * written to disk.
 */
import { describe, it, beforeEach } from 'node:test';
import assert from 'node:assert/strict';
import * as path from 'path';
import * as os from 'os';
import * as fs from 'fs';
import { generate } from '../src/index';
import { schemaRegistry } from '../src/schema-to-ts';

// __dirname at runtime is dist-test/tests; project root is two levels up.
const SPEC_PATH = path.resolve(__dirname, '../../openapi.yaml');

// ---------------------------------------------------------------------------
// Full pipeline – sample openapi.yaml
// ---------------------------------------------------------------------------

describe('generate() – sample openapi.yaml', () => {
  let files: Record<string, string>;

  // Run generate() once; reuse results across tests in this suite.
  // We use a before-style approach: the first `it` sets the shared variable.
  // Using beforeEach would re-run the async generate call every test which is
  // slow. Instead we use a module-level promise resolved before the suite.

  // Node test runner doesn't support async describe, so we seed files via a
  // helper called at the top of each test, guarded by a flag.
  let ready = false;
  async function ensureFiles() {
    if (!ready) {
      schemaRegistry.clear();
      files = await generate({ inputPath: SPEC_PATH, outputDir: '/tmp/unused' });
      ready = true;
    }
  }

  it('produces exactly the three expected output files', async () => {
    await ensureFiles();
    assert.deepEqual(Object.keys(files).sort(), ['_helpers.ts', 'client.ts', 'types.ts']);
  });

  // -------------------------------------------------------------------------
  // _helpers.ts
  // -------------------------------------------------------------------------

  it('_helpers.ts exports createChannel', async () => {
    await ensureFiles();
    assert.match(files['_helpers.ts'], /export function createChannel/);
  });

  it('_helpers.ts contains the _DONE symbol', async () => {
    await ensureFiles();
    assert.match(files['_helpers.ts'], /_DONE/);
  });

  it('_helpers.ts contains the async iter generator', async () => {
    await ensureFiles();
    assert.match(files['_helpers.ts'], /async \*iter\(\)/);
  });

  // -------------------------------------------------------------------------
  // types.ts
  // -------------------------------------------------------------------------

  it('types.ts starts with the generated-by comment', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /\/\/ Generated by sse-codegen/);
  });

  it('types.ts contains PostChatCompletionsParams interface', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /PostChatCompletionsParams/);
  });

  it('types.ts contains PostChatCompletionsEvent type alias', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /PostChatCompletionsEvent/);
  });

  it('types.ts emits the three SSE event variants', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /"message"/);
    assert.match(files['types.ts'], /"done"/);
    assert.match(files['types.ts'], /"error"/);
  });

  it('types.ts emits ChatMessage referenced schema', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /ChatMessage/);
  });

  it('types.ts emits ApiError referenced schema', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /ApiError/);
  });

  it('types.ts emits ChatCompletionRequest referenced schema', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /ChatCompletionRequest/);
  });

  it('types.ts body property uses ChatCompletionRequest type', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /body: ChatCompletionRequest/);
  });

  it('types.ts ApiError has required code and message fields', async () => {
    await ensureFiles();
    // Required fields should have no question mark
    const apiErrorBlock = files['types.ts'].match(/ApiError[\s\S]*?\{([\s\S]*?)\}/)?.[1] ?? '';
    assert.match(apiErrorBlock, /code: string/);
    assert.match(apiErrorBlock, /message: string/);
    assert.doesNotMatch(apiErrorBlock, /code\?/);
    assert.doesNotMatch(apiErrorBlock, /message\?/);
  });

  it('types.ts ChatMessage has optional role and finish_reason fields', async () => {
    await ensureFiles();
    assert.match(files['types.ts'], /role\?: string/);
    assert.match(files['types.ts'], /finish_reason\?: string/);
  });

  // -------------------------------------------------------------------------
  // client.ts
  // -------------------------------------------------------------------------

  it('client.ts starts with the generated-by comment', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /\/\/ Generated by sse-codegen/);
  });

  it('client.ts imports fetchEventSource', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /from '@microsoft\/fetch-event-source'/);
  });

  it('client.ts imports createChannel from _helpers', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /from '.\/\_helpers'/);
  });

  it('client.ts imports the Params and Event types', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /PostChatCompletionsParams/);
    assert.match(files['client.ts'], /PostChatCompletionsEvent/);
  });

  it('client.ts sets BASE_URL from the spec server', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /const BASE_URL = "https:\/\/api\.example\.com\/v1"/);
  });

  it('client.ts exports postChatCompletions function', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /export async function\* postChatCompletions/);
  });

  it('client.ts uses POST method', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /method: 'POST'/);
  });

  it('client.ts JSON.stringifies params.body', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /JSON\.stringify\(params\.body\)/);
  });

  it('client.ts dispatches on msg.event === "message"', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /msg\.event === "message"/);
  });

  it('client.ts dispatches on msg.event === "done"', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /msg\.event === "done"/);
  });

  it('client.ts dispatches on msg.event === "error"', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /msg\.event === "error"/);
  });

  it('client.ts JSON.parses message data (application/json)', async () => {
    await ensureFiles();
    // The message variant has contentMediaType:application/json so must JSON.parse
    assert.match(files['client.ts'], /JSON\.parse\(msg\.data\)/);
  });

  it('client.ts yields from ch.iter()', async () => {
    await ensureFiles();
    assert.match(files['client.ts'], /yield\* ch\.iter\(\)/);
  });
});

// ---------------------------------------------------------------------------
// generate() error handling
// ---------------------------------------------------------------------------

describe('generate() – error handling', () => {
  it('throws when no SSE operations are found', async () => {
    // Write a minimal spec with no SSE content to a temp file
    const dir = path.join(os.tmpdir(), `sse-test-${Date.now()}`);
    fs.mkdirSync(dir);
    const specPath = path.join(dir, 'empty.yaml');
    fs.writeFileSync(specPath, [
      'openapi: 3.1.0',
      'info:',
      '  title: Empty',
      '  version: 1.0.0',
      'paths:',
      '  /ping:',
      '    get:',
      '      responses:',
      '        "200":',
      '          description: ok',
    ].join('\n'));
    await assert.rejects(
      () => generate({ inputPath: specPath, outputDir: dir }),
      /No SSE operations found/
    );
    fs.rmSync(dir, { recursive: true });
  });

  it('respects a baseUrl override over the spec server URL', async () => {
    const files = await generate({
      inputPath: SPEC_PATH,
      outputDir: '/tmp/unused',
      baseUrl: 'https://override.example.com',
    });
    assert.match(files['client.ts'], /https:\/\/override\.example\.com/);
    assert.doesNotMatch(files['client.ts'], /api\.example\.com/);
  });
});

// ---------------------------------------------------------------------------
// generate() – writeFiles integration (real disk output)
// ---------------------------------------------------------------------------

describe('generate() + writeFiles – disk output', () => {
  it('writes all three files to the output directory', async () => {
    const { writeFiles } = await import('../src/emit');
    const dir = path.join(os.tmpdir(), `sse-test-${Date.now()}`);
    schemaRegistry.clear();
    const files = await generate({ inputPath: SPEC_PATH, outputDir: dir });
    writeFiles(dir, files);
    for (const name of ['_helpers.ts', 'types.ts', 'client.ts']) {
      assert.ok(fs.existsSync(path.join(dir, name)), `${name} should exist`);
    }
    fs.rmSync(dir, { recursive: true });
  });
});
