import { loadSpec } from './parse';
import { extractSseOperations } from './extract';
import {
  generateEventType,
  generateParamsType,
  generateReferencedSchemaTypes,
  toPascalCase,
} from './typegen';
import { generateFunction } from './fngen';
import { emitToString } from './emit';
import { schemaRegistry } from './schema-to-ts';
import { HELPERS_TEMPLATE } from './helpers-template';

export interface GenerateOptions {
  inputPath: string;
  outputDir: string;
  baseUrl?: string;
}

export async function generate(
  opts: GenerateOptions,
): Promise<Record<string, string>> {
  const spec = await loadSpec(opts.inputPath);
  const ops = extractSseOperations(spec);

  if (ops.length === 0) {
    throw new Error('No SSE operations found in spec');
  }

  const baseUrl = opts.baseUrl || spec.servers?.[0]?.url || '';

  // Clear registry for fresh generation
  schemaRegistry.clear();

  // Generate operation-level types (this populates schemaRegistry with referenced schemas)
  const opTypeNodes: import('typescript').Node[] = [];
  for (const op of ops) {
    const paramsNode = generateParamsType(op);
    if (paramsNode) opTypeNodes.push(paramsNode);
    opTypeNodes.push(...generateEventType(op));
  }

  // After generating operation types, emit any referenced schemas discovered during traversal
  const referencedSchemaNodes = generateReferencedSchemaTypes();

  const typesContent =
    `// Generated by sse-codegen\n\n` +
    emitToString([...referencedSchemaNodes, ...opTypeNodes]);

  // Generate client functions (string-based)
  const fnStrings = ops.map((op) => generateFunction(op, baseUrl));

  const opTypeNames = ops.flatMap((op) => {
    const prefix = toPascalCase(op.operationId);
    const hasParams = op.parameters.length > 0 || op.requestBody !== undefined;
    const names = [...(hasParams ? [`${prefix}Params`] : []), `${prefix}Event`];
    if (
      op.itemSchema.oneOf &&
      op.itemSchema.discriminator?.propertyName === 'event'
    ) {
      for (const variant of op.itemSchema.oneOf) {
        const eventConst = variant.properties?.event?.const;
        if (typeof eventConst === 'string') {
          names.push(`${prefix}${toPascalCase(eventConst)}Event`);
        }
      }
    }
    return names;
  });

  const clientHeader = [
    '// Generated by sse-codegen',
    `import { fetchEventSource } from '@microsoft/fetch-event-source';`,
    `import { createChannel } from './_helpers';`,
    `import type { ${opTypeNames.join(', ')} } from './types';`,
    '',
    `const BASE_URL = ${JSON.stringify(baseUrl)};`,
    '',
    '',
  ].join('\n');

  const clientContent = clientHeader + fnStrings.join('\n\n');

  return {
    '_helpers.ts': HELPERS_TEMPLATE.trimStart(),
    'types.ts': typesContent,
    'client.ts': clientContent,
  };
}
